apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmJ5dGV3aXNlLmNvbS5teSI6IHsKICAgICAgImF1dGgiOiAiYlhwaGJHazZWM0ZHTkdKSlFYUmxjV05JY2tKMFYyTkRRbTQyYUhoM09XbEJaVmQxZUdORGJERnlkVWhpYlU1WFIxa3hiVFZ4Tm5SUFZVbFVaQzlsT0hoellrRlpSUT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
